### ISSUE TITLE
How to optimize SVBRDF(Texture)

### ISSUE THREAD

**Issue by tim37021** [BachiLi/redner#10]
it generates mipmap automatically in pyredner module.  I am not quite sure how I can optimize texture texels

```python
text = torch.tensor(np.ones()*0.5, requires_grad=True, device=pyredner.device()))
material.diffuse_reflectance = pyredner.Texture(text)
...
optimizer = torch.optim.Adam([text])

for ...:
  // I have to add retain_graph=True here to get it work.
  render()
  loss.backward(retain_graph=True)
  // text update correctly, but rendered image does not change..
  // then text will be gradually broken...
  optimizer.step()

```

**Comment by tim37021** [comment]
should I re-assign text to diffuse_reflectance??
it seems the texels is not updated even if text is change.
```python
scene.materials[-2].diffuse_reflectance = pyredner.Texture(text)
```

**Comment by tim37021** [comment]
If I try to rebuild the graph by reassign texture to diffuse reflectance. 
Cuda memory access error will occur

**Comment by BachiLi** [comment]
Closing this issue. Feel free to reopen if there's other questions.
