### ISSUE TITLE
Unable to optimize for normal map

### ISSUE THREAD

**Issue by mworchel** [BachiLi/redner#113]
I encountered an issue when optimizing for a normal map and distilled a minimal working as notebook (see attachment)

Basically, in this experiment, we have a known SVBRDF (normals, diffuse albedo, roughness, specular albedo) as well as a fixed and known configuration of light and camera. We use this configuration to generate a rendering of a square patch composed of the above mentioned material. The goal is now to generate a re-rendering of that target image by keeping everything but the normal map fixed. We initialize a new normal map randomly, re-render the scene and compare the rendering to the target image using the L1 loss. By iteratively optimizing the new normal map in this way, we obtain a normal map that, while it doesn't look like the original one, reproduces the target image in the given configuration.

Now the issue: The loss decreases and the image starts to look like the target until around iteration 40 (learning rate of 5e-2), where the loss suddenly starts to increase and then settles on a value (or keeps increasing slowly). You can see that at the moment when the loss increases, the image starts to become dark at the place where a specular highlight is supposed to be and the normal map turns into a dark blueish color in this area as if the normals start to point away from the area light.

Now I totally don't know what's going on and if it might be an error on my side but I was able to reproduce the issue in various configurations. I tried to decrease the learning rate (issue appears later), estimate only the x and y coordinates of the normals or try to constrain the normals to the upper hemisphere, all without success. I looked at the gradient images and after the corruption, they seem to vanish in the specular highlight area as if the discrepancy between both renderings is not propagated back properly.

Would be great if you could have a look into it and try to reproduce it. Am I not correctly using some part of the API?

[normal-estimation.zip](https://github.com/BachiLi/redner/files/4246060/normal-estimation.zip)

**Comment by BachiLi** [comment]
Something is wrong with the specular highlight derivatives. Let me check.

**Comment by BachiLi** [comment]
Should be fixed in 0.3.14.
https://colab.research.google.com/drive/1CJtpLNsFJfn6SQm-OS5Iu5nlDY4x8bMl
There was a bug in the BRDF derivatives in my code.
Thanks a lot for reporting!

**Comment by mworchel** [comment]
Thanks for looking into that so quickly and fixing it! I also tested it with a more tough setup where the light and camera position change every iteration and it seems to be (slowly) converging to the correct normal map. Before your fix this particular setup was completely broken.
