### ISSUE TITLE
Camera Calibration with Redner

### ISSUE THREAD

**Issue by dawnKalo** [BachiLi/redner#115]
Hi,

I'm looking for a way to calibrate the camera parameters with Redner with respect to the location of projected vertices on the image.
I have corresponding key points between the target and the mesh,
I.e I can express it by 3D mesh point & projected 2D  { (x,y,z) , (ximage,yimage)}
I want to get the camera parameters.

I'm aware to the DLT algorithm for getting the camera parameters, such that I found
the matrix A:
P_projected = A P_xyz
where P_projected expressed in homogenous coordinates.

but I don't know how to translate this A to the camera parameters of Redner.
Alternatively, is there a way in Redner for optimizing with respect to the project points?
The pose tutorial focuses on difference between the intensity of the pixels and I'm looking for optimizing with respect to the location of the pixels.

**Comment by dawnKalo** [comment]
@Guptajakala

I saw your post here:
https://github.com/BachiLi/redner/issues/83

Can you please explain how to convert the matrix:
```
K = [fx, 0, cx]
    [0, fy, cy]
    [0 , 0, 1]
```
To intrinsic matrix in Redner?

**Comment by dawnKalo** [comment]
OK, I figured it out.
Instead of applying DLT on 3D point to 2D in pixel index - [0,H] x [0,W], the range is [-1, 1/aspect_ratio) x [1, -1/aspect_ratio), then we get 2 decomposed matrices K and RT.
Redner should get K as intrinsic_mat and inverse of RT as cam_to_world.

In any case, there is a bug when one sends numpy array to Redner with type of np.float64 instead of np.float32 (It was my major problem in debugging it).
I suggest to make conversion in order to avoid it for other users.

**Comment by BachiLi** [comment]
I added some checks in
https://github.com/BachiLi/redner/commit/cb72aa5c5f086fc0a9d5d8a87dfe4cf64cbf498b

Let me know if this is what you suggested or not and pull requests are always welcome.

**Comment by dawnKalo** [comment]
> I added some checks in
> [cb72aa5](https://github.com/BachiLi/redner/commit/cb72aa5c5f086fc0a9d5d8a87dfe4cf64cbf498b)
> 
> Let me know if this is what you suggested or not and pull requests are always welcome.

Yes, it is.

**Comment by chongli-uw** [comment]
Hi @BachiLi and @dawnKalo  , thank you for the great discussion. I am facing the inverse problem, with a known camera intrinsics, how to set the `intrinsic_mat ` argument in redner `Camera` object? 

Say I have a known
```
K = [fx, 0, cx]
    [0, fy, cy]
    [0 , 0, 1]
```
and the size of the image (H, W), how to convert K to `intrinsic_mat `?
