### ISSUE TITLE
Tutorial reference to file is broken 

### ISSUE THREAD

**Issue by Skorkmaz88** [BachiLi/redner#125]
In the notebook implementation of material_and_lights.ipynb,  referenced EXR file no longer exists in the given location :  [http://gl.ict.usc.edu/Data/HighResProbes/probes/grace-new.exr](http://gl.ict.usc.edu/Data/HighResProbes/probes/grace-new.exr)

**Comment by BachiLi** [comment]
Fixed! Thanks for reporting.
