### ISSUE TITLE
Pip install not compatible with python 3.8?

### ISSUE THREAD

**Issue by adambielski** [BachiLi/redner#134]
For python 3.8 environment, `pip install redner` returns the following error:
```
ERROR: Could not find a version that satisfies the requirement redner-gpu (from versions: none)
ERROR: No matching distribution found for redner-gpu
```

Pip version:
```
pip --version
pip 20.0.2 from /home/a/.conda/envs/torch2/lib/python3.8/site-packages/pip (python 3.8)
```

Seems to work fine with python 3.7

**Comment by BachiLi** [comment]
I just released the 3.8 pip packages. Let me know if it works for you or not!

**Comment by mworchel** [comment]
Hi @BachiLi,

I tested the 3.8 pip packages and at least for me it works (still Windows 10).

**Comment by justdark** [comment]
python 3.9 have the same problem

**Comment by huww98** [comment]
Hi @BachiLi, Could you please also release the pip packages for Python 3.9?

**Comment by damilareisaac** [comment]
Hi, 
This is currently not working on python3.8 or later versions for Mac.
