### ISSUE TITLE
UV mapping looks to be wrong

### ISSUE THREAD

**Issue by dawnKalo** [BachiLi/redner#135]
Hi,

I have obj file.
I've tried to render it with both Redner and Blender.
The object has vertices, texture coordinate (uvs), polygons indices, polygons texture indices (uv_indices

This is the Image that I get in Blender:
![Screen Shot 2020-06-15 at 16 12 08](https://user-images.githubusercontent.com/62008004/84661411-f907ac80-af22-11ea-9b61-68311ac4b171.png)
.

This is the image I got with redner:

![Screen Shot 2020-06-15 at 16 10 05](https://user-images.githubusercontent.com/62008004/84661205-ae863000-af22-11ea-9247-bdf0c3c6da02.png)

I gave it the following parameters (which corresponded to obj data)
material = pyredner.Material(diffuse_reflectance = texture)
obj = pyredner.Object(vertices=vertices, indices=indices, uvs=uvs, uv_indices=uv_indices, normals=normals, material=material)

**Comment by dawnKalo** [comment]
The problem was that the UV was upside down.
Thanks Anyway.

**Comment by BachiLi** [comment]
FYI there is a flag "flip_tex_coords" in the obj loader which flips the uv for you.
