### ISSUE TITLE
Can redner handle transparent material like a glass cup?

### ISSUE THREAD

**Issue by magicknight** [BachiLi/redner#139]
Hi,

We have a project like this:

![img](https://raw.githubusercontent.com/magicknight/zvt/master/tests/glass_cup.png)

We would like to back propagate to find the thickness of the glass.Just wanna know if it is possible to do this on redner?
Thank you!

**Comment by BachiLi** [comment]
Hey,

At the moment glasses are not supported. It may not be difficult to add glasses as an alternative BSDF, but our edge sampling may not work right away for producing low variances. I am currently rewriting redner to support compile-time automatic differentiation and after that, I will revisit/improve the edge sampling. It may take several months, but adding glasses should be easier after that. 

At the same time, I recommend taking a look at Mitsuba 2 (https://github.com/mitsuba-renderer/mitsuba2) and the path reparametrization plugin. The reparametrization method should be more suitable for this task, though I am not sure if their implementation supports transparent materials.

**Comment by magicknight** [comment]
Thank you BachiLi.
