### ISSUE TITLE
Importing Pyredner

### ISSUE THREAD

**Issue by firewater334** [BachiLi/redner#14]
Hi,

I attempted to run the first tutorial, yet despite pyredner being on my computer, my compiler is unable to detect pyredner and states "No module named pyredner".  Any thoughts?  If it matters, I configured and generated the necessary dependencies through CMake and did not make install via the terminal.

**Comment by BachiLi** [comment]
you should make install.

**Comment by BachiLi** [comment]
Closing this issue. Feel free to reopen if the problem persist.
