### ISSUE TITLE
Error in pyredner.load_obj()

### ISSUE THREAD

**Issue by Spandan-Madan** [BachiLi/redner#141]
Having trouble importing OBJ files downloaded from the internet. Obj files tried:-

[obj file 1](https://free3d.com/3d-model/ac-cobra-269-83668.html)
[obj file 2](https://free3d.com/3d-model/audi-r8-spyder-22646.html)
[obj file 3](https://free3d.com/3d-model/low-poly-car-40967.html)

It seems the error happens everytime the obj file comes with an accompanying blend file. Not sure if this is relevant. But error happens consistently. Google Colab file to reproduce error -

https://colab.research.google.com/drive/1kp-MapMEHFRMoafu4ogRr_Qj2phTG8q5?usp=sharing

Error stack:

```
AssertionError                            Traceback (most recent call last)
<ipython-input-12-9a3101ae9c67> in <module>()
----> 1 objects = pyredner.load_obj('Audi_R8_2017.obj', return_objects=True)

/usr/local/lib/python3.6/dist-packages/pyredner/load_obj.py in load_obj(filename, obj_group, flip_tex_coords, use_common_indices, return_objects, device)
    220                         f -= 1
    221                     return f
--> 222                 assert(len(splitted) <= 5)
    223                 def get_vertex_id(indices):
    224                     pi = parse_face_index(indices, 0)

AssertionError: 

```

**Comment by BachiLi** [comment]
There are polygons more than 4 vertices in your .obj files, and I didn't bother to write a polygon splitting code. If you are using Blender I suggest you split the polygons in Blender obj exporter.

**Comment by Spandan-Madan** [comment]
Can confirm this solves the problem. While exporting in blender I checked the "triangulate faces" option!

Thanks!
