### ISSUE TITLE
Installing Redner without CUDA

### ISSUE THREAD

**Issue by abhinavvs** [BachiLi/redner#15]
I am trying to build and install redner **without** CUDA (which was mentioned as an optional requirement). I have all other dependencies installed. When I run `ccmake .. ` and try to configure, I get the following error: 
> CUDA_TOOLKIT_ROOT_DIR not found or specified

Even when I use a CMake gui and configure, I get this error: 

> CUDA_TOOLKIT_ROOT_DIR not found or specified
Could NOT find CUDA (missing: CUDA_TOOLKIT_ROOT_DIR CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "10")
Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
Configuring done

Is there a quick fix for this problem? In general, how to get redner up and running without CUDA support?

**Comment by BachiLi** [comment]
CUDA is not required and the not found message should be a warning instead of an error.
You should still be able to generate a makefile.

**Comment by BachiLi** [comment]
Closing this issue. Feel free to reopen if the problem persist.
