### ISSUE TITLE
Error When Importing "pyredner_tensorflow"

### ISSUE THREAD

**Issue by linub** [BachiLi/redner#153]
Hi, 
I installed redner with "pip install redner-gpu" command in my tensorflow environment and it installed fine with no error message. But when I import pyredner_tensorflow I get this error:

> tensorflow.python.framework.errors_impl.NotFoundError: /home/linub/Desktop/deep/tf-gpu-2.4/lib/python3.8/site-packages/libredner_tf_data_ptr_no_cxx11_abi.so: undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb

tensorflow: 2.4 gpu version
OS: ubuntu 20.04
python: 3.8

Please help! Thanks.

**Comment by chrysmun** [comment]
pip install redner-gpu==0.4.25

going back to version 0.4.25 solves this issue for me. after that the import works fine.
