### ISSUE TITLE
Can I use extrinsic camera parameters in redner?

### ISSUE THREAD

**Issue by joy-alen** [BachiLi/redner#164]
Hi,
Just as an intrinsic matrix can be used for the redner camera, is it possible to use extrinsic parameters as well?

**Comment by joy-alen** [comment]
Extrinsic parameters can be used with the cam_to_world parameter in the pyredner camera Class. However the extrinsic matrix is -1  multiplied to the first column as that of the matrix used for mitsuba's.

**Comment by lith0613** [comment]
> first column

Hi, can you share your method about how to transform the R,t and the camera K into the correct value in Redner ? [150](https://github.com/BachiLi/redner/issues/150)
