### ISSUE TITLE
build from source problem

### ISSUE THREAD

**Issue by iszihan** [BachiLi/redner#173]
Hello, I got this error after building from source, am wondering if anyone encountered the same issue? 
import redner
ImportError: libtbb.so.2: cannot open shared object file: No such file or directory

**Comment by baibizhe** [comment]
Hello . I am facing the same error. Would you mind telling me how you solved this ?

**Comment by xiangruhuang** [comment]
I solved it using `sudo apt install libtbb-dev` on ubuntu.

**Comment by zzbuzzard** [comment]
The above didn't work for me, but `sudo apt install libtbb2` did :)
