### ISSUE TITLE
Error: copy-list-initialization cannot use a constructor marked "explicit"

### ISSUE THREAD

**Issue by GH-HOME** [BachiLi/redner#18]
When I make the project, the following error occurs.

error: copy-list-initialization cannot use a constructor marked "explicit"

`That error happens when compiling "material.h"`

`inline std::tuple<int, int, int> get_diffuse_size() const {
        return {diffuse_reflectance.width,
                diffuse_reflectance.height,
                diffuse_reflectance.num_levels};
    }`

I also test `int w=diffuse_reflectance.width`, same error occurs.

Could you please give me some suggestions?

**Comment by GH-HOME** [comment]
I don't whether this problem is related to embree lib since I have not found any class defined by "explicit".
The embree version I used is 3.5.0 for Linux.

**Comment by GH-HOME** [comment]
Problem solved. For people facing the same problem, please refer this.

I change the code:
Original version:
`inline std::tuple<int, int, int> get_diffuse_size() const { 
return {diffuse_reflectance.width, diffuse_reflectance.height, diffuse_reflectance.num_levels};
 }`

Current version:
```
inline std::tuple<int, int, int> get_diffuse_size() const {
        return std::make_tuple(diffuse_reflectance.width,
                diffuse_reflectance.height,
                diffuse_reflectance.num_levels);
    }
```

**Comment by BachiLi** [comment]
Looks like the compiler you're using didn't implement the recent change in C++ standard (http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4387.html).
I've fixed the issue using your suggestion. Thanks a lot for reporting!
