### ISSUE TITLE
Square Root NaN Bug

### ISSUE THREAD

**Issue by budmonde** [BachiLi/redner#21]
There's a bug in the `envmap` code where it's possible to get a NaN evaluated due to a `sqrt` function call at the following callsite:

https://github.com/BachiLi/redner/blob/7a6074db84940b68cdc8a98a7a5cd2a3a42aee52/envmap.h#L262

It seems that if `local_dir.y` equals `1`, then `1 - square(local_dir.y)` evaluates to `-0.0000` which when taken the square root of gives you a `NaN` error.

**Comment by budmonde** [comment]
I made a temporary hack fix by changing line 262 to something like:
```c++
auto sin_theta = sqrt(max((double)0, 1 - square(local_dir.y)));
```
This issue with `sqrt` taking bad inputs could potentially be in different callsites as well(?) Not sure what the proper fix should be. Perhaps a `safq_sqrt` function?

**Comment by BachiLi** [comment]
I pushed a fix here:
https://github.com/BachiLi/redner/commit/7df39b53cf2107bb4305d70129b5debef69967fc
Let me know if it fixes it.

**Comment by budmonde** [comment]
Resolved.
