### ISSUE TITLE
Importing Pyredner outside build folder

### ISSUE THREAD

**Issue by firewater334** [BachiLi/redner#22]
Hi,

I noticed that the import pyredner command solely works when I am under the build folder of redner.  I cannot be in another folder under that build folder as well ((e.g. if I am under redner/build/test) I cannot run "import pyredner" under the test folder..  Is there a reason for this?  Thank you!

Here is the error message below:
>>> import pyredner
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abhinav/anaconda3/lib/python3.7/site-packages/pyredner/__init__.py", line 9, in <module>
    from .render_pytorch import *
  File "/home/abhinav/anaconda3/lib/python3.7/site-packages/pyredner/render_pytorch.py", line 4, in <module>
    import redner
ImportError: libembree3.so.3: cannot open shared object file: No such file or directory

**Comment by BachiLi** [comment]
The error message is complaining that it cannot find Embree. Copy libembree3.so.3 to a directory in LD_LIBRARY_PATH or install embree.

**Comment by firewater334** [comment]
Hi,

I copied libembree3.so.3 to LD_LIBRARY_PATH, and then I received a similar error for optix prime.  I repeated the same step for liboptix_prime.so.1, and then when I tried to import pyredner from outside the build folder, I received the following error:

>>> import pyredner
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abhinav/redner/pyredner/__init__.py", line 9, in <module>
    from .render_pytorch import *
  File "/home/abhinav/redner/pyredner/render_pytorch.py", line 4, in <module>
    import redner
ImportError: /usr/local/cuda-10.0/lib64/libembree3.so.3: undefined symbol: _ZN3tbb10interface78internal15task_arena_base24internal_max_concurrencyEPKNS0_10task_arenaE
>>> 


Note that I have set the path for embree in my FindEmbree.CMake file to:
set(EMBREE_LIBRARY "/home/abhinav/embree-3.5.0.x86_64.linux/lib/libembree3.so.3")
set(EMBREE_INCLUDE_PATH "/home/abhinav/embree-3.5.0.x86_64.linux/include/")

Do you know what is causing the error, and why does import pyredner work specifically under the build folder of redner?  Thank you!

**Comment by BachiLi** [comment]
The prebuilt Embree binary requires tbb (Intel's multithreading library). This is complaining that it couldn't find a function in tbb. If you are using Ubuntu, maybe try "sudo apt-get install libtbb-dev".

**Comment by firewater334** [comment]
Hi,

I ran the command successfully, but I am still getting the same error.  Any other thoughts?  Thanks!

**Comment by BachiLi** [comment]
Can you compile/run any embree examples?

**Comment by firewater334** [comment]
I can and have run a tutorial, but I must launch Python in the build folder of redner.

**Comment by BachiLi** [comment]
Not my code. Can you run the tutorials in Embree?
https://github.com/embree/embree/tree/master/tutorials

**Comment by firewater334** [comment]
I see it says: "The Embree tutorials are installed into the /usr/bin/embree3 folder. Specify the full path to the tutorials to start them"  Do you know where I specify this path to try running an Embree tutorial?

**Comment by firewater334** [comment]
Actually, I just attempted to compile and received a CMake error saying that the source directory "/home/abhinav/embree-3.5.0.x86_64.linux" does not appear to contain CMakeLists.txt

**Comment by firewater334** [comment]
Actually, I just attempted to compile and received a CMake error saying that the source directory "/home/abhinav/embree-3.5.0.x86_64.linux" does not appear to contain CMakeLists.txt.  Which CMakeLists.txt file do I use/how do I get that file in the embree directory?

**Comment by BachiLi** [comment]
Well, can you run the tutorials in Embree?

**Comment by firewater334** [comment]
Sorry for my lack of understanding, but how do I run let's say the triangle_geometry tutorial?  Do I make the triangle_geometry.cpp file an executable under that directory and run that with ./?  For I receive an error when trying to make it an executable.  Thank you!

**Comment by abhinavvs** [comment]
Hi, 
I have been trying to install redner (with CUDA support) on my GPU. I am having similar problems as those raised in this issue. I followed the instructions exactly as given on the wiki. The "make install" command ran without any errors.

I was wondering if we need to install embree separately, or does the installation of redner automatically takes care of that? 

Any help will be much appreciated. Thank you in advance!

**Comment by BachiLi** [comment]
What exactly is the problem? In theory the installation now automatically installs Embree as well but I'm not sure if I've written a robust installation script.

**Comment by BachiLi** [comment]
Ok turns out I didn't. I think I just fixed it. Can you pull from the latest commit and try again?

**Comment by abhinavvs** [comment]
Thank you for checking it. I pulled again from the latest commit. Then went over the installation steps again (which happened without any issues). However I get the same error when I try to execute one of the tutorials: 

> [Traceback](most recent call last):
  File "01_optimize_single_triangle.py", line 2, in <module>
    import pyredner
  File "/home/abhinav/anaconda3/lib/python3.7/site-packages/pyredner/__init__.py", line 2, in <module>
    from .camera import *
  File "/home/abhinav/anaconda3/lib/python3.7/site-packages/pyredner/camera.py", line 4, in <module>
    import redner
ImportError: libembree3.so.3: cannot open shared object file: No such file or directory

However, I am able to run the tutorials from within the "build" folder. I am running this on:
- Linux OS
- CUDA 10
- OptiX 5.1
- Python 3.7

I had previously tried installing embree independently (for redner) but am not sure if I did that right either. I am relatively new to ray tracing softwares. So haven't done any of this before.

**Comment by BachiLi** [comment]
Can you remove your embree installation and try again?

**Comment by abhinavvs** [comment]
Should i simply just delete the embree folder (which i installed previously)? or is there a way to uninstall embree?

**Comment by BachiLi** [comment]
It depends on how you installed it. You should remove libembree.so and the embree3 include directory. My guess is they are located at /usr/local/lib and /usr/local/include

**Comment by abhinavvs** [comment]
There are 3 embree related files in /usr/local/lib:
"libembree3.so", "libembree3.so.3", and "libembree.3.so.3.4.0". Should I remove them all?

**Comment by BachiLi** [comment]
Yes

**Comment by abhinavvs** [comment]
Ok. I did that. "make install -j 8" threw an error after about 33% completion: 

> [ 33%] Building NVCC (Device) object CMakeFiles/redner.dir/redner_generated_pathtracer.cpp.o
In file included from /home/abhinav/redner/primary_contribution.cpp:2:0:
/home/abhinav/redner/scene.h:16:10: fatal error: embree3/rtcore.h: No such file or directory
 #include <embree3/rtcore.h>
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
CMake Error at redner_generated_primary_contribution.cpp.o.cmake:219 (message):
  Error generating
  /home/abhinav/redner/build/CMakeFiles/redner.dir//./redner_generated_primary_contribution.cpp.o
> CMakeFiles/redner.dir/build.make:3243: recipe for target 'CMakeFiles/redner.dir/redner_generated_primary_contribution.cpp.o' failed
make[2]: *** [CMakeFiles/redner.dir/redner_generated_primary_contribution.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /home/abhinav/redner/envmap.cpp:2:0:
/home/abhinav/redner/scene.h:16:10: fatal error: embree3/rtcore.h: No such file or directory
 #include <embree3/rtcore.h>
          ^~~~~~~~~~~~~~~~~~
.
.
.
          ^~~~~~~~~~~~~~~~~~
compilation terminated.
CMake Error at redner_generated_pathtracer.cpp.o.cmake:219 (message):
  Error generating
  /home/abhinav/redner/build/CMakeFiles/redner.dir//./redner_generated_pathtracer.cpp.o
CMakeFiles/redner.dir/build.make:2909: recipe for target 'CMakeFiles/redner.dir/redner_generated_pathtracer.cpp.o' failed
make[2]: *** [CMakeFiles/redner.dir/redner_generated_pathtracer.cpp.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/redner.dir/all' failed
make[1]: *** [CMakeFiles/redner.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

I can paste in the full error message if needed.

**Comment by abhinavvs** [comment]
Ok, so I deleted the build folder and try to build and install again. I faced the following errors when I tried to build (configure in ccmake):

> Embree not found in the system. Building from scratch.
 CMake Error at embree/common/cmake/ispc.cmake:54 (MESSAGE):
   Intel SPMD Compiler (ISPC) not found.  Disable EMBREE_ISPC_SUPPORT or
   install ISPC.
 Call Stack (most recent call first):
   embree/CMakeLists.txt:396 (INCLUDE)

I remember this happening in the previous installation as well. Then I turned OFF the EMBREE_ISPC_SUPPORT flag using ccmake and then built (which seemed to work then).

**Comment by BachiLi** [comment]
Cool. The error is expected since ispc is not installed. We do not use any ispc-related features in Embree, so it is fine. You may also need to turn off EMBREE_TUTORIAL.

**Comment by abhinavvs** [comment]
I turned off both the flags, but am still getting this error:  

> Embree not found in the system. Building from scratch.

**Comment by abhinavvs** [comment]
Ok. Now the installation went fine (after I turned off the above mentioned embree flags). But I still get the same error. 

> ImportError: libembree3.so.3: cannot open shared object file: No such file or directory

I just checked that "libembree3.so.3" is there in /usr/local/lib. 
However LD_LIBRARY_PATH=/usr/local/cuda-10.0/lib64.

Is this the issue? If so, how do i fix it?

**Comment by BachiLi** [comment]
Yay!

**Comment by abhinavvs** [comment]
So, I have another question (unrelated with this issue). 

I have installed redner without tensorflow support (currently have only PyTorch installed in the system). But if I want to start using the tensorflow version, would I have to redo the installation from scratch after pulling from newer commits, i.e. configure, generate and the make install? 
This in fact applies to any of the newer functionalities introduced.

**Comment by BachiLi** [comment]
In theory you only need to make install again. Let me know if it doesn't work.

**Comment by BachiLi** [comment]
I suppose I can close this issue now. For those who have similar issues, checkout your LD_LIBRARY_PATH.
