### ISSUE TITLE
More NaN Issues

### ISSUE THREAD

**Issue by budmonde** [BachiLi/redner#28]
https://github.com/BachiLi/redner/blob/e46647a49b3618dc2c5d1b1c479b01098614ecf9/envmap.h#L265

Similar to #21, in the above code execution, there is a rare case where `lum_fy`, `lum_cy`, and `sin_theta` all are exactly 0. In this situation, the output of `envmap_pdf` returns `-nan`.

I'm not sure how this should be fixed. Any ideas?

**Comment by BachiLi** [comment]
I pushed a fix here:
https://github.com/BachiLi/redner/commit/7df39b53cf2107bb4305d70129b5debef69967fc
Let me know if it fixes it.

**Comment by budmonde** [comment]
Looks like the issue got resolved. Thanks!
