### ISSUE TITLE
How to debug the code

### ISSUE THREAD

**Issue by GH-HOME** [BachiLi/redner#29]
Hi, I just want to know your method to debug the pyrender, since it is written in C++, and we call it by python, how can I step in the cpp file in pyrender?

**Comment by BachiLi** [comment]
Hi,

One way to do this is to run python with your debugger (e.g. gdb python or lldb python), then do 'run file.py' in the debugger. Printfs and assertions are always helpful too ; )

**Comment by GH-HOME** [comment]
> Hi,
> 
> One way to do this is to run python with your debugger (e.g. gdb python or lldb python), then do 'run file.py' in the debugger. Printfs and assertions are always helpful too ; )

Thanks. Also, do you know if there is any way to debug mitsuba? Actually I want to write my algorithm as a mitsuba plugin and then apply your code to compute the gradient with regard to the rendering parameter.

**Comment by BachiLi** [comment]
You can also use gdb or lldb or even visual studio debugger to launch Mitsuba

**Comment by tim37021** [comment]
use gdb/lldb to debug python. and load the symbol file to your debugger.

**Comment by BachiLi** [comment]
Closing this issue. Feel free to reopen if there are more questions.
