### ISSUE TITLE
Asserting even if CUDA is installed

### ISSUE THREAD

**Issue by jayavanth** [BachiLi/redner#3]
```
$ python3 test_shadow_light.py        
python3: /home/jay/redner/scene.cpp:79: Scene::Scene(const Camera&, const std::vector<const Shape*>&, const std::vector<const Material*>&, const std::vector<const Light*>&, bool): Assertion `false' failed.
[1]    9201 abort (core dumped)  python3 test_shadow_light.py
```
I'm getting this assert for all tests. I have CUDA installed and enabled during CMake.

```
#ifdef __NVCC__
    ...
#else 
    assert(false)
#endif
```
Here's the snippet from `scene.cpp`. I'm guessing nvcc is not being used to compile `scene.cpp`

**Comment by jayavanth** [comment]
Sweet! It works now

**Comment by BachiLi** [comment]
Interesting. What is the compute capability of your GPU? Do you know which line the code crashed?

**Comment by jayavanth** [comment]
I have a K40 (3.5) and TitanX (5.2) and it's failing on both of them. My guess is it's crashing on the CPU. I'll find out at what line it's crashing

**Comment by jayavanth** [comment]
It's crashing on line 64 `test_shadow_light.py`
```
img = render(0, *args)
```

**Comment by BachiLi** [comment]
Can you maybe run a debugger on python (e.g. gdb python, run test_shadow_light.py), and find out which line in the C++ that goes run?

**Comment by jayavanth** [comment]
Here's the line:
```
Thread 1 "python3" received signal SIGBUS, Bus error.
Scene::Scene (this=0x22aaa80, camera=..., shapes=std::vector of length 3, capacity 3 = {...}, 
    materials=std::vector of length 2, capacity 2 = {...}, lights=std::vector of length 1, capacity 1 = {...}, use_gpu=<optimized out>)
    at /home/jay/redner/scene.cpp:137
137	            light_areas[light_id] = area_sum;
(gdb) p area_sum
$1 = 0.040000001192092904
(gdb) p light_id
$2 = 0
(gdb) p light_areas
$3 = {use_gpu = true, data = 0x2308941000, count = 1}
```

**Comment by BachiLi** [comment]
I supposed it's because I didn't synchronize the kernel. I pushed some fix. Let me know if it fixes the problem.

**Comment by jayavanth** [comment]
The test runs fine on the CPU with your latest push. But I get this on either GPUs

```
Thread 51 "python3" received signal SIGBUS, Bus error.
[Switching to Thread 0x7fff5affd700 (LWP 17870)]
0x00007fffbe9091f2 in DScene::DScene (this=0x7fff7800b3b0, camera=..., shapes=std::vector of length 3, capacity 3 = {...}, 
    materials=std::vector of length 2, capacity 2 = {...}, lights=std::vector of length 1, capacity 1 = {...}, use_gpu=<optimized out>)
    at /home/jay/redner/scene.cpp:202
202	            this->shapes[shape_id] = *shapes[shape_id]
```

**Comment by BachiLi** [comment]
Probably the same issue. I pushed another fix that adds more synchronizations. Let me know if there's more issues.

**Comment by jayavanth** [comment]
All tests are running fine now. Awesome! Thanks!

**Comment by Skorkmaz88** [comment]
I started to have this assertion error after using the Redner a while , scene.cpp , line 125,  when using calling path tracing functions from Jupyter notebook , but not from .py files so far.

**Comment by BachiLi** [comment]
You probably did `pip install redner` instead of `pip install redner-gpu`.
Try `pip uninstall redner` and reinstall the GPU version.

**Comment by Skorkmaz88** [comment]
I actually initially installed GPU version and then after awhile had issues, however that is probably an issue happened in my system, oddly py files were running smoothly still, and they were using the same environment. Reinstalling redner-gpu seems to be working now.
