### ISSUE TITLE
Back-face culling

### ISSUE THREAD

**Issue by loudonclear** [BachiLi/redner#33]
Is there a way to disable back-face culling currently?

Feature would be greatly appreciated!

**Comment by BachiLi** [comment]
Not at the moment. This is not too difficult to add. I will append this to the TODO list.

**Comment by BachiLi** [comment]
Actually, by default backface culling is disabled. I guess you are looking for the "two_sided" parameter in the material ( https://github.com/BachiLi/redner/blob/master/pyredner/material.py#L9 ). Set it to True and you should be able to see something.

That being said it would still be useful to have an option for backface culling.

**Comment by BachiLi** [comment]
Redner by default doesn't do backface culling, but the default shading model is one-sided. You can make the shading two-sided by setting material.two_sided = True.

Enabling backface culling is in fact quite tricky and I'm not sure if it's worthwhile to have it in redner.  Embree supports backface culling but requires a special build that turns on RTC_BACKFACE_CULLING. Optix prime doesn't support backface culling. Optix does support backface culling, so in the future if we move from Optix prime to Optix we might consider having backface culling.

I'll make this a wontfix at the moment but feel free to reopen if you have a strong case for this.
