### ISSUE TITLE
About the living-room scenes

### ISSUE THREAD

**Issue by numericalBoy** [BachiLi/redner#34]
I tried to reproduce your optimization process on the room scenes (as presented in your paper and your recent paper,  https://niessnerlab.org/projects/azinovic2019inverse.html )

I download the original scene from 
https://benedikt-bitterli.me/resources/mitsuba/living-room-3.zip

To make it readable for redner:
1. I changed "sphere" light to "area light" defined in an obj file.
2. I changed "Glass" material to "diffuse"
3. I debugged the "toworld" ("lookat") vectors (to replace the matrix representation) in Mitsuba GUI.
...
the modified XML can be load by Mitsuba.  

However, it still failed to be load by redner at 

https://github.com/BachiLi/redner/blob/master/buffer.h#L86

Would you like to share the living-room-3 scene you used in your paper (maybe the room scene in your newest CVPR paper as well) in this repo?

I would love to send you an email about this if you feel more comfortable.

BTW: I've been reading your code throughout. Really solid work,  thumbs up!

**Comment by BachiLi** [comment]
Looks like a bug. I will check it and upload the scene to this repo.
The CVPR paper uses a different renderer for many reasons. The scenes are just a bunch of Wavefront obj files. I am not sure if I can share the scenes, I would check with Dejan Azinović about this.

**Comment by numericalBoy** [comment]
Thank you for your instant reply! @BachiLi

**Comment by BachiLi** [comment]
Sorry for the non-instant update: you can look at tests/test_living_room.py now. I had to fix a few bugs related to camera derivatives for this scene to make it working. Let me know if you have any issues.

**Comment by BachiLi** [comment]
Closing this issue. Feel free to reopen if there are more questions.
