### ISSUE TITLE
Turn on/off the edge sampling technique. 

### ISSUE THREAD

**Issue by numericalBoy** [BachiLi/redner#37]
Edge sampling is a great thing to make the differential visibility (path traced!) work!

"It also depends on your material model: if you have discontinuities in your procedural shader, then you need some kind of edge sampling or prefiltering. Index of refraction of dielectric materials might also cause discontinuities."

To my knowledge, some rendering parameters do not need this, such as the continuous parameters like diffuseTex for a continuous surface in a static scene.
Edge sampling is heavy. This repo is very active (a good thing!)

As mentioned by you in previous issues answer,

"To turn off edge sampling, I would add "return;" at these two lines:
https://github.com/BachiLi/redner/blob/master/edge.cpp#L235
https://github.com/BachiLi/redner/blob/master/edge.cpp#L644
I might add a flag to do this in the future."

The code line you provided in the issue answer is not accurate now.  
Perhaps make it as an option?   -- a bool parameter in "render.options" (python) ?

It would be very convenient to test or develop new algorithms based on "redner".

_Originally posted by @BachiLi in https://github.com/BachiLi/redner/issues/27#issuecomment-475243832_

**Comment by BachiLi** [comment]
Done. See RenderFunction.serialize_scene.
Hopefully in the future I will engineer the edge sampling code enough to make the overhead small.

**Comment by BachiLi** [comment]
Done. See RenderFunction.serialize_scene() and https://github.com/BachiLi/redner/commit/25057374e8f8fa771713c594e37f3f5cc2fc8ba2
I haven't tested it so let me know if it breaks.
Hopefully with more engineering in the future I can make the overhead small enough.

**Comment by numericalBoy** [comment]
Thank you so much!
BTW:  I have been doing my research with this repo a lot.  I would love to contribute some code!  If you have a road map for this repo, please let me know!

**Comment by BachiLi** [comment]
Sounds great! I don't have a precise road map yet, but most of the "wish list" is at the bottom of README.md and issues. Plus I am recently playing with simplifying the derivative accumulation code. Feel free to send any pull requests or ask questions.

**Comment by vcl-pku** [comment]
I had implemented several features in your list.  Some are too difficult for me. Some are relatively ok.  Let's reconnect after this recent key submission ddl.  
Thank you again for sharing the code! 
I regard this repo(your paper) as a new direction but with unlimited research potential!

**Comment by numericalBoy** [comment]
I had implemented several features on your list. 
Some are too difficult for me. Some are relatively ok. Let's reconnect after this recent key submission ddl.
Thank you again for sharing the code! 
I regard this repo(your paper) as a new direction but with unlimited research potential!

**Comment by BachiLi** [comment]
Closing since this is done.
