### ISSUE TITLE
Optimizing a square

### ISSUE THREAD

**Issue by jayavanth** [BachiLi/redner#4]
To understand the code, I tried changing vertices to render a square instead of a triangle in the scene. Here's how I modified `test_single_traingle.py`:
```
@@ -26,16 +26,16 @@ mat_grey = pyredner.Material(\
     diffuse_reflectance = torch.tensor([0.5, 0.5, 0.5],
     device = pyredner.get_device()))
 materials = [mat_grey]
-vertices = torch.tensor([[-1.7,1.0,0.0], [1.0,1.0,0.0], [-0.5,-1.0,0.0]],
+vertices = torch.tensor([[-1.0,2.0,0.0], [2.0,2.0,0.0], [-1.0,-1.0,0.0], [2.0,-1.0,0.0]],
                         device = pyredner.get_device())
-indices = torch.tensor([[0, 1, 2]], dtype = torch.int32,
+indices = torch.tensor([[0, 1, 2, 3]], dtype = torch.int32,
                        device = pyredner.get_device())
...
...
...
 # Perturb the scene, this is our initial guess
-shape_triangle.vertices = torch.tensor(\
-    [[-2.0,1.5,0.3], [0.9,1.2,-0.3], [-0.4,-1.4,0.2]],
+shape_square.vertices = torch.tensor(\
+    [[-1.0,1.0,0.3], [1.0,2.0,0.3], [0.0,-1.0,0.3], [2.0,0.0,0.3]],

```
But I'm still seeing a triangle in `init.png` and `target.png`. Do you know what I might be doing wrong?

[init.png](https://imgur.com/a/9LWmDow)
[target.png](https://imgur.com/a/Y5XJoDA)

**Comment by BachiLi** [comment]
Hi,
We currently only support triangle mesh, which means that the indices of the shape needs to be a Mx3 torch integer tensor. If you want to render a quad, the easiest way is to split it into two triangles.

I added more comments in the single triangle test and made it the first tutorial. Take a look at [tutorials/01_optimize_single_triangle.py](https://github.com/BachiLi/redner/blob/master/tutorials/01_optimize_single_triangle.py) and you might have a better idea. Thanks!

**Comment by jayavanth** [comment]
Thanks! that was helpful
