### ISSUE TITLE
Tutorial 02 results: teapot not aligned

### ISSUE THREAD

**Issue by MatisHudon** [BachiLi/redner#40]
I am trying to run the tutorials. I have tried the second tutorial, changing nothing from the code. However I cannot get as satisfying results as the ones presented. I have tried different learning rates but never got the teapot correctly aligned in the end. Can anyone confirm that with the current version of the code, this tutorial is running correctly and outputting expected result?
Thanks

**Comment by BachiLi** [comment]
probably a regression again. i'll check

**Comment by BachiLi** [comment]
It seems to be caused by a grazing angle safe guard I put in bsdf evaluation (quite surprising such small changes can make this big difference). I remove the safe guard and the teapots align on my side. Let me know if the latest commit works for you or not.

**Comment by MatisHudon** [comment]
Okay I will let you know as soon as possible thank you!

**Comment by MatisHudon** [comment]
Okay this fixed the issue, thank you.
