### ISSUE TITLE
How to use for rendering 2d vertex coordinates into binary mask?

### ISSUE THREAD

**Issue by shivamsaboo17** [BachiLi/redner#41]
How can I use this library to render 2d image from coordinates (polygon). I have predictions in form of vertex coordinates (batch, num_points, x, y) and I want to render it into 2D binary mask. Is is possible? I want to achive similar thing as done in optimizing triangle tutorial but I dont have information about material, lighting and texture because I want just a binary mask. Any insight would be really helpful!

**Comment by BachiLi** [comment]
This is totally possible. Will write an example. I also plan to implement a 2D version of redner but I'll give you the example first ; )

**Comment by shivamsaboo17** [comment]
Thanks a lot. Would be looking forward to it!

**Comment by shivamsaboo17** [comment]
Hi did you have time to write the example for 2d rendering?

**Comment by BachiLi** [comment]
Sorry, occupied by something else as always. Give me two or three days.

**Comment by shivamsaboo17** [comment]
No problem! I completely understand.

**Comment by BachiLi** [comment]
Done. See examples/two_d_mesh.py for optimization of a quad and a triangle (similar to test_two_triangles.py).
Right now redner doesn't support general polygons, so you would need to triangulate your polygons. Something like Delauny triangulation (e.g. scipy.spatial.Delaunay) might be helpful. Depending on the structure of your polygons there might be an easier way to convert.

**Comment by BachiLi** [comment]
Oops. I didn't see that you need a binary mask instead of color. Replace
```
channels = [redner.channels.diffuse_reflectance]
```
with
```
channels = [redner.channels.alpha]
```
to have a 1D alpha channel output.

**Comment by shivamsaboo17** [comment]
Thanks a lot!
