### ISSUE TITLE
UV texture map appears to be wrong

### ISSUE THREAD

**Issue by MatisHudon** [BachiLi/redner#43]
Hello, 

I have been trying to load a model with a non trivial texture Map (Kd_map), I think there is a problem with the texture mapping. To be sure I altered the chessboard texture of the teapot with asymmetries and rendered it with redner, I also opened the same model with the modified texture in meshlab, and saw that the mapping were really different. I've tried to reverse "(1-x)" the uvs_pool when loading the obj file but I couldn't get the same mapping as in meshlab so it appears more complex than that.

**Comment by BachiLi** [comment]
Hi,

If there is something wrong I think it's in the uv map of the model but not the texture mapping code. Can you share the model, textures, and expected results?

**Comment by MatisHudon** [comment]
Hi, 

I understand your concern. However, I have tried many obj/mtl with texture and not one loads correctly. For example a Free obj from CGTrader: [https://www.cgtrader.com/items/234469/download-page](here). If you load it in meshlab you can see the expected result (note that you might need to edit file paths in the mtl file).  You can load it with the pose estimation tutorial with this camera setup: 

```# Setup camera
cam = pyredner.Camera(position = torch.tensor([0.0, 80.0, 200.0]),
                      look_at = torch.tensor([0.0, 80.0, 0.0]),
                      up = torch.tensor([0.0, 1.0, 0.0]),
                      fov = torch.tensor([55.0]), # in degree
                      clip_near = 1e-2, # needs to > 0
                      resolution = (256, 256),
                      fisheye = False)

**Comment by BachiLi** [comment]
Looks like a bug in the obj loader. Let me check.

**Comment by BachiLi** [comment]
Looks like obj textures conventionally have (0, 0) at lower left, so I need to flip y coordinate to obtain correct uv mapping. I added a flag "flip_tex_coords" in load_obj and set the default to true. Now the rendering matches MeshLab's result:

rendering
![target](https://user-images.githubusercontent.com/951021/60183393-c91a5180-9858-11e9-9e86-ba10a253b5a5.png)

meshlab
<img width="294" alt="meshlab_screenshot" src="https://user-images.githubusercontent.com/951021/60183420-d8010400-9858-11e9-9917-9dae03490856.png">

**Comment by MatisHudon** [comment]
I was suspecting something like this. Perfect it works now, thank you!
