### ISSUE TITLE
Build issue with mitsuba.pyc

### ISSUE THREAD

**Issue by tstullich** [BachiLi/redner#44]
Hi,

I am getting the following error when trying to build redner on my Linux machine running OpenSUSE Tumbleweed:

>byte-compiling /usr/lib/python2.7/site-packages/pyredner/load_mitsuba.py to load_mitsuba.pyc
>  File "/usr/lib/python2.7/site-packages/pyredner/load_mitsuba.py", line 18
>    ret = value @ ret
>                ^
> SyntaxError: invalid syntax
>
>byte-compiling /usr/lib/python2.7/site-packages/pyredner/transform.py to transform.pyc
>  File "/usr/lib/python2.7/site-packages/pyredner/transform.py", line 80
>    return rot_z @ (rot_y @ rot_x)

My guess is that my version of python is set incorrectly in the build files somewhere, but I checked my CMake configurations with ccmake and have not found anything thus far. Would you know how I can solve this problem?

**Comment by BachiLi** [comment]
The cmake file assumes ```python``` is an alias to python-3. I'll fix this at some point, but currently I would suggest to install miniconda with python 3, or alias python python3.

**Comment by tstullich** [comment]
I tried installing again using conda this time and I am still getting the same error. This time the proper version is selected during the CMake configuration, but during the `install_lib` installation step python 2.7 is still used to compile the byte code for mitsuba.pyc. Is there perhaps another build script that gets run when running that task and should I look into fixing the error there? I included a screenshot below:
![errors](https://user-images.githubusercontent.com/894276/60821707-5d16e200-a1a4-11e9-96b1-6bdee09ac9bf.png)

**Comment by BachiLi** [comment]
If you type ```python``` in the command line, does it execute python2 or python3?

**Comment by tstullich** [comment]
When I am in the anaconda environment it shows as being 3.7
`Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
`

**Comment by BachiLi** [comment]
The problem is at the following line
```
install(CODE "execute_process(COMMAND python ${CMAKE_CURRENT_SOURCE_DIR}/setup.py install
                              WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR})")
```
where CMake still uses python2.7 in the system to execute the setup script.
Did you include the initialization scripts added by the conda installer to your shell profile?
e.g. Do you see the following two lines in ~/.profile, ~/.bashrc, ~/.bash_profile, ...etc?
```
. /home/tim/src/miniconda3/etc/profile.d/conda.sh
conda activate
```
If so, maybe try to restart the shell or relogin.

**Comment by tstullich** [comment]
Thanks for the prompt responses :) Yes, I actually just tried a clean build with cloning the project and that seems to have partially fixed this issue. However, I am now not able to build the OpenEXR library, which worked fine before. I attached another screenshot with the error. Sounds like the linker is not able to deal with a certain file, but I did not change any configurations in the CMake files for that. Do you have an idea on how to fix this?
![errors](https://user-images.githubusercontent.com/894276/60846446-bea87200-a1df-11e9-98c5-dc2fd5a7516c.png)

**Comment by BachiLi** [comment]
Seems related:
https://github.com/MTG/sms-tools/issues/85
https://github.com/pytorch/pytorch/issues/16683#issuecomment-459982988

**Comment by tstullich** [comment]
Hi, using the suggestion of renaming the Anaconda linker temporarily fixed things, however there is one more issue now. Should I open another issue for this?

When I now try to run the example I get the following error:
```
Traceback (most recent call last):
File "two_d_mesh.py", line 1, in <module>  import pyredner
 File "/home/tim/src/miniconda3/lib/python3.7/site-packages/pyredner/__init__.py", line 2, in <module> from .camera import *
 File "/home/tim/src/miniconda3/lib/python3.7/site-packages/pyredner/camera.py", line 4, in <module> import redner
ImportError: liboptix_prime.so.6.0.0: cannot open shared object file: No such file or directory
```

I have double checked that the files are where they are supposed to be and that I have permissions to access the shared objects. I included a screenshot of the CMake variables I set with ccmake. Would you happen to know what could be going wrong here?

![ccmake](https://user-images.githubusercontent.com/894276/62142091-f93c9080-b2ed-11e9-8a9a-86acecb62657.png)

**Comment by tstullich** [comment]
I am closing this issue for now since the initial issue was resolved. I will open a new issue for further discussion.
