### ISSUE TITLE
OpenEXR undefined symbol: _ZTIN7Iex_2_27BaseExcE

### ISSUE THREAD

**Issue by xtsdylyx** [BachiLi/redner#45]
Hi, I've met a problem when installing the newest version of redner(updated on 06/25/2019). I successfully installed redner in the previous version, but somehow the problem meets.

When trying the tutorials 1, I met problems like this:

>  Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
> Type "copyright", "credits" or "license" for more information.
> 
> IPython 7.5.0 -- An enhanced Interactive Python.
> 
> runfile('/media/yuanxun/E/code/redner/tutorials/01_optimize_single_triangle.py', wdir='/media/yuanxun/E/code/redner/tutorials')
> Traceback (most recent call last):
> 
>   File "<ipython-input-1-298e4e089826>", line 1, in <module>
>     runfile('/media/yuanxun/E/code/redner/tutorials/01_optimize_single_triangle.py', wdir='/media/yuanxun/E/code/redner/tutorials')
> 
>   File "/home/yuanxun/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
>     execfile(filename, namespace)
> 
>   File "/home/yuanxun/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "/media/yuanxun/E/code/redner/tutorials/01_optimize_single_triangle.py", line 2, in <module>
>     import pyredner
> 
>   File "/home/yuanxun/anaconda3/lib/python3.6/site-packages/pyredner/__init__.py", line 10, in <module>
>     from .image import *
> 
>   File "/home/yuanxun/anaconda3/lib/python3.6/site-packages/pyredner/image.py", line 2, in <module>
>     import OpenEXR
> 
> ImportError: /home/yuanxun/anaconda3/lib/python3.6/site-packages/OpenEXR.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN7Iex_2_27BaseExcE

I thinks there's problem in OpenEXRpython. When I want to import pyredner, this error happens. Error still exists after I trying changing the version of OpenEXR from 2.3 to 2.2. 

I'm using Anaconda with Python 3.6.  Hope for answer!

**Comment by BachiLi** [comment]
Most likely caused by a version confusion of OpenEXR (I bet every single person who worked on offline rendering had been through this). Try to remove all OpenEXR installation on your system and install it again.

**Comment by xtsdylyx** [comment]
@BachiLi Error still exists after I removing all OpenEXR installation. I deleted OpenEXR include file in location 'usr/local/include' and re-installed OpenEXR. I can't figure out where was the problem since I'm not familiar with it.

Here is my procedure:
    I. Delete all files I could find about OpenEXR.
    II. Download 'ilmbase-2.3.0.tar.gz' and 'openexr-2.3.0.tar.gz' in [https://github.com/openexr/openexr/releases](url). Following the steps in [https://github.com/openexr/openexr/blob/master/INSTALL.md](url), in detail:
> cd <source root>/IlmBase
> ./configure
> make
> make install
> 
> cd <source root>/OpenEXR
> ./configure
> make 
> make install

   III. Install redner, note that I set OPENEXR_INCLUDE_PATH in cmake-gui as ''usr/local/include".

After these, the error still exists when I import pyredner.
> Python 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)
> Type "copyright", "credits" or "license" for more information.
> 
> IPython 7.5.0 -- An enhanced Interactive Python.
> 
> import pyredner
> Traceback (most recent call last):
> 
>   File "<ipython-input-1-855e9eb508b0>", line 1, in <module>
>     import pyredner
> 
>   File "/home/yuanxun/anaconda3/lib/python3.6/site-packages/pyredner/__init__.py", line 10, in <module>
>     from .image import *
> 
>   File "/home/yuanxun/anaconda3/lib/python3.6/site-packages/pyredner/image.py", line 2, in <module>
>     import OpenEXR
> 
> ImportError: /home/yuanxun/anaconda3/lib/python3.6/site-packages/OpenEXR.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN7Iex_2_27BaseExcE

I really don't know where I was wrong? Didn't I remove OpenEXR completely? or I install a wrong version(2.3.0)? or I just install OpenEXR in a wrong way? 
Sorry to bother you again!

**Comment by BachiLi** [comment]
It still tries to link to openexr 2.27, so the link path is probably wrong. What is the OPENEXR_IEX_LIBRARY path in the cmake setting? What are the other paths related to openexr (you may need to turn on the advanced option)?

**Comment by xtsdylyx** [comment]
> It still tries to link to openexr 2.27, so the include or link path are still probably wrong. What is the OPENEXR_IEX_LIBRARY path in the cmake setting? What are the other paths related to openexr (you may need to turn on the advanced option)?

Thanks a lot! I found the problem! I need to set the include path to my anaconda3's include path since I install OpenEXR using Anaconda.
BTW, I have another problem. When I run the tutorials, I have an error: 

>   File "<ipython-input-2-298e4e089826>", line 1, in <module>
>     runfile('/media/yuanxun/E/code/redner/tutorials/01_optimize_single_triangle.py', wdir='/media/yuanxun/E/code/redner/tutorials')
> 
>   File "/home/yuanxun/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
>     execfile(filename, namespace)
> 
>   File "/home/yuanxun/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "/media/yuanxun/E/code/redner/tutorials/01_optimize_single_triangle.py", line 174, in <module>
>     "results/optimize_single_triangle/out.mp4"])
> 
>   File "/home/yuanxun/anaconda3/lib/python3.6/subprocess.py", line 287, in call
>     with Popen(*popenargs, **kwargs) as p:
> 
>   File "/home/yuanxun/anaconda3/lib/python3.6/subprocess.py", line 729, in __init__
>     restore_signals, start_new_session)
> 
>   File "/home/yuanxun/anaconda3/lib/python3.6/subprocess.py", line 1364, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> 
> FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg': 'ffmpeg'

Emm, where I should to download the 'ffmpeg'?

**Comment by BachiLi** [comment]
Assuming you are using ubuntu: https://www.faqforge.com/linux/how-to-install-ffmpeg-on-ubuntu-14-04/

**Comment by xtsdylyx** [comment]
Done! Also I'm hoping for the update for mini-batching!
