### ISSUE TITLE
Thrust Allocation Failure

### ISSUE THREAD

**Issue by PopcornPenguino** [BachiLi/redner#48]
I'm running into `assert(false);` @ thrust_utils.h:84. The forward pass goes through, loss gets calculated, but it fails when running the backwards pass.

```
python 01_optimize_single_triangle.py 
Scene construction, time: 0.05752 s
Forward pass, time: 0.04237 s
/home/jlafleche/miniconda3/envs/redner/lib/python3.6/site-packages/skimage/util/dtype.py:122: UserWarning: Possible precision loss when converting from float32 to uint8
  .format(dtypeobj_in, dtypeobj_out))
Scene construction, time: 0.01139 s
Forward pass, time: 0.04475 s
iteration: 0
Scene construction, time: 0.01407 s
Forward pass, time: 0.02298 s
loss: 758.4088134765625
python: /home/jlafleche/Projects/redner/thrust_utils.h:84: char* ThrustCachedAllocator::allocate(std::ptrdiff_t): Assertion `false' failed.
```

I solved the error by increasing the number of buffers for the GPU case to 2, but I wonder if you might have more insights into why the error comes up in the first place. Thanks!

**My configuration:**
Pytorch: 1.1.0
Embree: 3.5.2
Optix: 5.1.1
Cuda: 10.0
compiler: gcc-7

**GPUs:**
TitanXP
RTX 2080Ti

**Comment by BachiLi** [comment]
What's your thrust version?

**Comment by BachiLi** [comment]
The way we use thrust is very different now so this is likely resolved. I am closing this issue but feel free to reopen.
