### ISSUE TITLE
Usage of redner trainning in other network

### ISSUE THREAD

**Issue by xtsdylyx** [BachiLi/redner#50]
Thanks for this wonderful work! 
I met troubles when I tried to use redner as a differentiable render module in my whole networks. Given an image I,  I train an network X to predict the vertices corresponding to it. Network X includes an encoder to learn features about I to construct vertices.
So, I could get

> Pred_vertices = X(I)

Next, I want to use redner to learn textures & lighting via rendering the vertices to 2D plane. 
My original assume is that: redner achieves gradients about vertices & textures & lighting from loss between images, and gradients about vertices can be back passed to my encoder X. However, I got error like

>   File "/home/yuanxun/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 827, in runfile
>     execfile(filename, namespace)
> 
>   File "/home/yuanxun/anaconda3/lib/python3.6/site-packages/spyder_kernels/customize/spydercustomize.py", line 110, in execfile
>     exec(compile(f.read(), filename, 'exec'), namespace)
> 
>   File "/media/yuanxun/E/My Experiment/train.py", line 177, in <module>
>     train_loss.backward()
> 
>   File "/home/yuanxun/anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph)
> 
>   File "/home/yuanxun/anaconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
>     allow_unreachable=True)  # allow_unreachable flag
> 
> RuntimeError: Function RenderFunctionBackward returned an invalid gradient at index 5 - got [1, 3] but expected shape compatible with [1, 53215, 3]

I original thought I can use redner as another part of My whole network but found I thought it too simple.
I guess there's problem set in gradients BP between redner and X.  I think I need to write a _torch.autograd.Function_ wrapper API to get the gradients of vertices from _RenderFunction.backward()_ in _render_pytorch.py_ and return the gradients to my network X. But I found difficulties here, I really don't know how to achieve the gradients of redner. Could you tell me how to get the gradients computed by redner?
Thanks!

**Comment by BachiLi** [comment]
I don't see fundamental reason why this wouldn't work. If you can create a minimal example for me to debug that will be much easier.

**Comment by xtsdylyx** [comment]
I believe that could solve my problem. Thanks for your attention. Closed this issue.
