### ISSUE TITLE
gcc9 w/o cuda: `isfinite` undefined for `Real&`s

### ISSUE THREAD

**Issue by newkozlukov** [BachiLi/redner#51]
Compiling w/o CUDA, gcc and clang complained on `cpp`s about `isfintie` being only defined for vectors, not for reals.

- Option 1: include `<cmath>` in `cpp`s
- Option 2: adding `using std::isfinite` in `vector.h` instead (`vector.h` is included in all places that reference `isfinite`; worked for me)

**Comment by BachiLi** [comment]
These won't work for CUDA. I'll install gcc-9 to test this.

**Comment by BachiLi** [comment]
Sorry, I have no idea what I was talking about (it was 2am and I probably didn't see Option 2). Anyway I should have fixed this in https://github.com/BachiLi/redner/commit/1905ccb2148cdf8be360c6c60d9dd4b72dca7344. Thanks again!

**Comment by newkozlukov** [comment]
Checked, `master` builds fine for me now.
Thanks for your amazing research!
