### ISSUE TITLE
Optimization of shading normals : SVBRDF

### ISSUE THREAD

**Issue by AakashKT** [BachiLi/redner#52]
Hello,
In the test code for SVBRDF optimization, you are providing diffuse, roughness and specular maps.
 
However, I was wondering whether we can optimize normal maps the same way. Does the material model itself not use normal maps? 

Thanks.

**Comment by BachiLi** [comment]
There's no normal map support yet. We do have per-vertex normals though. It's not very hard to add normal map, so I can add this to my todo list.

**Comment by AakashKT** [comment]
Thank you!

**Comment by BachiLi** [comment]
Done. See https://github.com/BachiLi/redner/blob/master/tests/test_teapot_normal_map.py
![out](https://user-images.githubusercontent.com/951021/62995227-831f4a00-be14-11e9-95d2-b4a63d16633f.gif)

Still need to implement the Mitsuba parser for the normalmap bsdf though.

**Comment by BachiLi** [comment]
Close since it's implemented. Haven't implemented the Mitsuba part but let me know if there's a need for that.
