### ISSUE TITLE
Python OpenEXR Old Boost Dependency

### ISSUE THREAD

**Issue by tstullich** [BachiLi/redner#53]
I have tried running the `two_d_mesh.py` demo and run into an error regarding a missing boost library. Screenshot below:
![error](https://user-images.githubusercontent.com/894276/62209211-488bcb00-b399-11e9-8db8-46b95f5e5cbf.png)

Upon further inspection it seems to me that the `pythonopenexr` extension is trying to use a shared object of libboost_system that is below version 1.60. On my system I am unable to install any boost libraries below version 1.69 so it is not straightforward for me to install the necessary dependencies.

During the build phase no errors appear as well, so finding this error after the fact is a bit frustrating. Do you have any suggestions on how to go about fixing this?

**Comment by BachiLi** [comment]
Perhaps try reinstalling OpenEXR on your system? Make sure it links to the correct boost version.

**Comment by tstullich** [comment]
I have re-installed the OpenEXR extension but I do not think that's the issue since redner seems to be shipped with two submodules for OpenEXR support. The submodule pertaining to the python version compiles as expected and I do not see any references being made to any boost libraries in the code, so I am not sure where this dependency to `libboost_system` could be coming from.
Are there any other ways to solve this issue?

**Comment by BachiLi** [comment]
Could it be that you already have other openexr installed in your system? e.g. Maybe you have installed opencv?

**Comment by tstullich** [comment]
I solved this issue for now but through quite a hack. I manually set the missing symlinks such that the linker could pick up the shared objects of my current installation of OpenEXR. Doing this finally lets me run the examples, but I am not sure this will be portable in case my distro upgrades OpenEXR and the symlinks become invalid.
