### ISSUE TITLE
gpu.dockerfile err at the last RUN

### ISSUE THREAD

**Issue by lonelywm** [BachiLi/redner#55]
I Just mod the dockerfile as below

'add one line'
RUN sed -i 's|http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64|https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64|g'  /etc/apt/sources.list.d/cuda.list

'mod one line':
ARG OPTIX_VERSION=7.0.0 (from 5.1.0)

'err occurs':
Step 21/21 : RUN if [ -d "build" ]; then rm -rf build; fi     && mkdir build     && cd build     && cmake ..     && make install -j 8     && cd /     && rm -rf /app/build/
 ---> Running in f57283dc9ef4
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The CUDA compiler identification is NVIDIA 10.0.130
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- Found Python: /opt/conda/lib/libpython3.6m.so (found suitable version "3.6.9", minimum required is "3.6") found components:  Development
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found CUDA: /usr/local/cuda (found suitable version "10.0", minimum required is "10")
CMake Error: File /app/embree/kernels/rtcore_version.h.in does not exist.
CMake Error at embree/CMakeLists.txt:64 (CONFIGURE_FILE):
  CONFIGURE_FILE Problem configuring file

CMake Error: File /app/embree/kernels/hash.h.in does not exist.
CMake Error at embree/CMakeLists.txt:68 (CONFIGURE_FILE):
  CONFIGURE_FILE Problem configuring file

CMake Error at embree/CMakeLists.txt:93 (INCLUDE):
  INCLUDE could not find load file:

    test

CMake Error: File /app/embree/kernels/config.h.in does not exist.
CMake Error at embree/CMakeLists.txt:170 (CONFIGURE_FILE):
  CONFIGURE_FILE Problem configuring file

CMake Error at embree/CMakeLists.txt:209 (MESSAGE):
  Unsupported compiler: GNU

-- Configuring incomplete, errors occurred!
See also "/app/build/CMakeFiles/CMakeOutput.log".
See also "/app/build/CMakeFiles/CMakeError.log".
The command '/bin/sh -c if [ -d "build" ]; then rm -rf build; fi     && mkdir build     && cd build     && cmake ..     && make install -j 8     && cd /     && rm -rf /app/build/' returned a non-zero code: 1

**Comment by BachiLi** [comment]
I probably broke the dockerfiles in some recent commits. Just pushed a fix. Let me know if it works or not.

**Comment by BachiLi** [comment]
I also did some cleanup and updated the installation instruction. From now on please put the OptiX installation directory under ```redner``` instead of ```redner/dockerfiles/dependencies```.

**Comment by lonelywm** [comment]
It works well now, thank you.

**Comment by BachiLi** [comment]
Thanks!
