### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by HectorAnadon** [BachiLi/redner#6]
Hello!
Probably I am doing something wrong for installing redner. Here is the error I get when I run tutorials/01_optimize_single_triangle.py
`Traceback (most recent call last):
  File "tutorials/01_optimize_single_triangle.py", line 1, in <module>
    import pyredner
  File "/home/hleon/anaconda3/envs/render/lib/python3.6/site-packages/pyredner/__init__.py", line 7, in <module>
    from .render_pytorch import *
  File "/home/hleon/anaconda3/envs/render/lib/python3.6/site-packages/pyredner/render_pytorch.py", line 4, in <module>
    import redner
ImportError: libembree3.so.3: cannot open shared object file: No such file or directory
`
It seems I am not importing embree correctly, here are my cmake variables:
`set(EMBREE_LIBRARY "/usr/lib64/libembree3.so.3")
set(EMBREE_INCLUDE_PATH "/usr/include/embree3")`

Do you see something wrong? Any ideas why this can be happening? Thank you for your help!

**Comment by HectorAnadon** [comment]
Solved issue, the env variable LD_LIBRARY_PATH was not properly set to the path for the embree library.
However, I am having a problem, I believe it is optix related:
`Traceback (most recent call last):
  File "tutorials/01_optimize_single_triangle.py", line 6, in <module>
    import pyredner
  File "/home/hleon/anaconda3/envs/render/lib/python3.6/site-packages/pyredner/__init__.py", line 7, in <module>
    from .render_pytorch import *
  File "/home/hleon/anaconda3/envs/render/lib/python3.6/site-packages/pyredner/render_pytorch.py", line 4, in <module>
    import redner
ImportError: /home/hleon/anaconda3/envs/render/lib/python3.6/site-packages/redner.so: undefined symbol: rtpContextGetLastErrorString`
My cmake variables are as follows:
set(OptiX_INCLUDE "/home/hleon/NVIDIA-OptiX-SDK-5.1.1-linux64/include")
set(optix_LIBRARY "/home/hleon/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix.so")
set(optix_prime_LIBRARY "/home/hleon/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix.so")

**Comment by BachiLi** [comment]
I think it's the same problem: is the lib64 directory of optix in your LD_LIBRARY_PATH?

**Comment by HectorAnadon** [comment]
I does not work. It seems it is not importing correctly the headers. I tested Optix examples and they work. How did you install optix? I just did `sh NVIDIA-OptiX-SDK-5.1.1-linux64-25109142.sh`. What version do you have?
Thanks!

**Comment by BachiLi** [comment]
I see the problem now. You linked optix instead of optix prime. Try changing your optix_prime_LIBRARY variable to /home/hleon/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64/liboptix_prime.so

**Comment by HectorAnadon** [comment]
Great! Thank you! I did't even notice. Also I had to add `/home/hleon/NVIDIA-OptiX-SDK-5.1.1-linux64/lib64` to the $LD_LIBRARY_PATH variable, and it worked.
Thank you for your quick answers and congratulations for your project.
