### ISSUE TITLE
Issue when camera position is at origin

### ISSUE THREAD

**Issue by francoisruty** [BachiLi/redner#62]
Hello, I'm currently doing successful renders with redner. But now I want to do those same renders with camera at origin, so I put camera at origin and translate the object vertices by the exact same amount I translated the camera to get it to the origin.
It all works fine if I put camera position at [0, 0, 0.001] but when z coordinate goes below a certain threshold, the rendered image goes black.
I'm using the deferred rendering code from tutorial 04.

Do you have any idea as to why redner camera at origin would cause render to fail? (note: I don't have any error message, just a black image)

**Comment by BachiLi** [comment]
I think it's related to the near clipping plane of the camera. Try playing with the `clip_near` parameters e.g. by making it smaller. If it doesn't work it would be great if you can share your scene/script with me so I can take a look.

**Comment by francoisruty** [comment]
Here is the script (you just need to change the .ob path)
[script.zip](https://github.com/BachiLi/redner/files/3719665/script.zip)

Run it and you get an image with a grey cube
Then, edit line 98 and replace
camera_pos = torch.tensor([0.0, 0.0, 0.1])
with
camera_pos = torch.tensor([0.0, 0.0, 0.0])
and now you have a black image

I think it's not linked with clip_near, in this case the object distance from camera is much bigger than clip_near so nothing should be clipped

**Comment by BachiLi** [comment]
I printed out the center of the object and it was `tensor([-1.9073e-06, -1.9073e-06,  3.8147e-06])`. Since the center of the object is used as the `look_at` position, the camera direction becomes zero if you put the camera position the same place, so you're not pointing anywhere. This is why you get a black image.

**Comment by francoisruty** [comment]
wow noobie mistake from me, thanks, you're right!
