### ISSUE TITLE
Docker Image Build Issue

### ISSUE THREAD

**Issue by lesnikow** [BachiLi/redner#67]
Hello, I'm having an issue when trying to build the Docker image with the CPU Dockerfile. All steps seem to build find, except for the last step of compiling the C/C++ code. I'm getting build errors that look like this:

```
[ 42%] Built target math
[ 42%] Building CXX object embree/kernels/CMakeFiles/embree_avx2.dir/__/__/geometry/curve_intersector_virtual.cpp.avx2.cpp.o
[ 43%] Building CXX object embree/kernels/CMakeFiles/embree_avx2.dir/__/__/bvh/bvh_intersector1_bvh4.cpp.avx2.cpp.o
[ 43%] Building CXX object embree/kernels/CMakeFiles/embree_avx2.dir/__/__/common/scene_user_geometry.cpp.avx2.cpp.o
[ 43%] Building CXX object embree/kernels/CMakeFiles/embree_avx2.dir/__/__/common/scene_instance.cpp.avx2.cpp.o
[ 43%] Building CXX object embree/kernels/CMakeFiles/embree_avx2.dir/__/__/common/scene_triangle_mesh.cpp.avx2.cpp.o
[ 44%] Building CXX object embree/kernels/CMakeFiles/embree_avx2.dir/__/__/common/scene_quad_mesh.cpp.avx2.cpp.o
[ 44%] Building CXX object embree/kernels/CMakeFiles/embree_avx2.dir/__/__/common/scene_curves.cpp.avx2.cpp.o
[ 45%] Linking CXX static library ../../libsimd.a
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
make[2]: *** [pyredner_tensorflow/custom_ops/CMakeFiles/redner_tf_data_ptr.dir/data_ptr.cc.o] Error 4
pyredner_tensorflow/custom_ops/CMakeFiles/redner_tf_data_ptr.dir/build.make:62: recipe for target 'pyredner_tensorflow/custom_ops/CMakeFiles/redner_tf_data_ptr.dir/data_ptr.cc.o' failed
CMakeFiles/Makefile2:1586: recipe for target 'pyredner_tensorflow/custom_ops/CMakeFiles/redner_tf_data_ptr.dir/all' failed
make[1]: *** [pyredner_tensorflow/custom_ops/CMakeFiles/redner_tf_data_ptr.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 45%] Building CXX object embree/kernels/CMakeFiles/embree_avx2.dir/__/__/common/scene_line_segments.cpp.avx2.cpp.o
[ 45%] Built target simd
[ 46%] Building CXX object embree/kernels/CMakeFiles/embree_avx2.dir/__/__/common/scene_grid_mesh.cpp.avx2.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-7/README.Bugs> for instructions.
...
```
This is resulting in the build to take significantly longer than ~30-40 minutes quoted on my relatively modern machine. 

I'd be perfectly happy to just use PyTorch for this too, if the TF dependency is an issue. Any suggestions or ideas? Thanks!

**Comment by francoisruty** [comment]
hi @lesnikow  how much RAM do you have? this looks like a RAM issue (not having enough)
(cpu.Dockerfile works fine on my side but I have a lot of RAM)

**Comment by francoisruty** [comment]
(googling "c++: internal compiler error: Killed (program cc1plus)" yields many results that point towards not having not enough RAM, I think your problem is not related to redner)

**Comment by lesnikow** [comment]
Hi @francoisruty 16GB on my laptop where I was building. Good to know.

**Comment by lesnikow** [comment]
I see, good to know. Let me try following some of those threads for solutions and write back if I run into further redner specific issues.

**Comment by francoisruty** [comment]
ok FYI the build works on my side but I'm using a hetzner.com server with 64 GB RAM so I have no clue what is the minimum amount necessary

**Comment by BachiLi** [comment]
Any luck with this? I'm glad to help if none of above works.

**Comment by lesnikow** [comment]
Thanks! Let me try to build again with `make -j8` or similar, and get back if I run into problems.

**Comment by BachiLi** [comment]
Just FYI by "change `make -j8`" I meant changing it to `make -j2` or just `make`. Sorry for the confusion.

**Comment by lesnikow** [comment]
Not a problem, makes sense, thanks!

**Comment by BachiLi** [comment]
@lesnikow If you're still interested, try `pip install redner-gpu` instead of building from source.

**Comment by lesnikow** [comment]
@BachiLi Nice! Let me try that the next time I try to run, looks very helpful to have it pip installable.

**Comment by BachiLi** [comment]
Closing since this is not relevant now. We don't build embree so most likely the memory issue has gone away. Feel free to reopen though.
