### ISSUE TITLE
Support for lens distortion

### ISSUE THREAD

**Issue by nkyriazis** [BachiLi/redner#74]
In my understanding, the only thing missing in Redner wrt e.g. OpenCV camera specification is the lens distortion model. Are you planning on supporting something like the radial and tangential distortion model of OpenCV?

Some thoughts: OpenCV has closed form formulas for the distortion whereas you would ideally need closed form formulas of undistortion (not that common, but plausible) to get the rays. Perhaps the [Inverse Function Therom](https://en.wikipedia.org/wiki/Inverse_function_theorem) could be of help there for the distortion/undistortion in ndc. Still, I've found that actually ADing the iterative (Newton-Raphson) inversion of distortion does trick for "reasonable" distortion parameterizations.

**Comment by nkyriazis** [comment]
Perhaps one way out of this is to allow the user to define the rays to be accumulated for each pixel, if the pipeline can accommodate this, instead of a parametric camera.

**Comment by BachiLi** [comment]
Good question. I would love to have distortion models and certainly can spend some time on this. You're correct that the lens distortion models need to be invertible in order for us to differentiate it in our system. I imagine that it wouldn't be too hard to incorporate some kind of polynomial radial distortion models to redner. Like you said it can either be done using implicit function theorem or directly differentiating the iterative solver for the inversion.

Programmable camera models are trickier due to how the edge sampling works. I don't see a way yet without engaging with the C++ code or me writing a full-blown compiler. I need to think about them harder.

**Comment by BachiLi** [comment]
For OpenCV's radial distortion model we can actually just use a cubic equation solver and there is a closed-form. This should be pretty easy to do. Not so sure about the tangential distortion, I'll need to check if there is a closed-form inversion.

**Comment by BachiLi** [comment]
Found a paper addressing the inversion: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4934233/
I'll implement it sometime this week or next week.

**Comment by BachiLi** [comment]
Hmm the article doesn't address tangential distortion. I might have to implement the iterative solver.

**Comment by BachiLi** [comment]
OK after a more thorough survey I think the iterative solver approach is the more feasible solution (the magical inverse formula I dreamed for didn't exist, and the iteration usually converge in ~5 iterations). The differentiation is not too complex. Like you said we can apply implicit function theorem.

**Comment by nkyriazis** [comment]
That's great to hear!

A note on solving. Like I said, solving works well for reasonable distortions. This means that for pixels around the center it's usually simple and fast to get an exact solution. Ideally, the whole surface should be solved by considering neighboring good solutions, in a flood-fill fashion, which hurts parallellism. Each pixel can be safely solved independently for mild distortions. I've added you to a private repo where I use Eigen AD to undistort. Have a look at detail.hpp. I'm sure you already have a plan on how to implement it exactly. You might still find it helpful.

Thanks for looking into that! It would be a great addition!

**Comment by nkyriazis** [comment]
Have you given this any thought? Would you care to provide some pointers on how one might introduce this in Redner so that we could perhaps give it a go?

**Comment by BachiLi** [comment]
Hey sorry for the silence. I was just about to work on this these days. Took me a while to cleanup the todo list.

**Comment by BachiLi** [comment]
0.4.7 should have this feature. The performance is not great for larger distortion yet but can be improved.
See https://github.com/BachiLi/redner/blob/master/tests/test_camera_distortion.py for an example.

![out](https://user-images.githubusercontent.com/951021/78211192-48892100-747a-11ea-89a7-95c34d8cffd9.gif)

Let me know if you have other suggestions or have found any issues.

**Comment by nkyriazis** [comment]
That is great news! We will make use of it and report back.

**Comment by nkyriazis** [comment]
Thanks for the addition!
