### ISSUE TITLE
Linkage Issue After Moving To Version 0.0.2

### ISSUE THREAD

**Issue by tstullich** [BachiLi/redner#76]
I updated my fork after seeing that a version bump has been made to version 0.0.2, but now I am having issues at runtime when the python module needs to load the needed OpenEXR libs. The error I get is this:

`OpenEXR.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN4half5_eLutE`

I tried fixing this by updating the `openexr_link_args` list in the new `setup.py` script to include all of the shared libraries in the `redner-dependencies` submodule, yet the error persists. Is there something else that I am not including correctly that I am missing?

**Comment by BachiLi** [comment]
The new version is supposed to link OpenEXR statically:
https://github.com/BachiLi/redner/blob/master/setup.py#L131
https://github.com/BachiLi/redner/blob/master/setup.py#L172
I was in the process of writing the build instruction. In theory now you just need to:
```
git submodule update --init --recursive
python setup.py install
```
and all the dependencies will be included.

**Comment by BachiLi** [comment]
I was missing a few libraries. Try again.

**Comment by BachiLi** [comment]
See https://github.com/BachiLi/redner/wiki/Installation for building instructions.

**Comment by BachiLi** [comment]
OK I can reproduce this on Linux (I was testing this on a machine with OpenEXR installed). Let me see if I can fix it.

**Comment by BachiLi** [comment]
Found the issue, I misunderstood the rule of linking when it comes to linking a static library to produce a shared library. Finding a cross-platform solution now.

**Comment by tstullich** [comment]
Ok, good to know that this is not only an issue on my end. I found out that the missing symbol comes from `libIlmImf-2_3_s.a` according to [this](https://bugzilla.redhat.com/show_bug.cgi?id=165729) archived post from a Redhat forum. Perhaps this helps in narrowing down the problem for a solution. I'll continue working on this in the morning.

**Comment by BachiLi** [comment]
Should be fixed now.

**Comment by tstullich** [comment]
Yup, looks like things are working again. Closing this issue since it has been resolved
