### ISSUE TITLE
Gaussian pyramid loss

### ISSUE THREAD

**Issue by prathik-naidu** [BachiLi/redner#8]
Hi,

Thanks for the awesome work! I was curious about your implementation of Gaussian pyramid loss referenced in section 5.1 of your paper. I couldn't seem to find it in the code base – is there a particular file that I could look which has this implementation? It seems like you only used this for one of the figures so wasn't sure if you have code for this?

Thanks!

**Comment by BachiLi** [comment]
Checkout https://github.com/BachiLi/redner/wiki/Tutorial-5%3A-coarse-to-fine-estimation

**Comment by BachiLi** [comment]
Closing this issue. Feel free to reopen if there's other questions.
