### ISSUE TITLE
render to get RGBD at once

### ISSUE THREAD

**Issue by Guptajakala** [BachiLi/redner#82]
Hi, First thanks for this awesome repo.

I'm wondering if there is a way to render RGBD images at one rendering pass? Currently I have found examples either about only RGB rendering (render_albedo) or depth only (render_g_buffer), which means I may need to first run render_albedo to get RGB and run a second pass render_g_buffer to get depth. Am I correct?

**Comment by Guptajakala** [comment]
Found the solution in source code.

**Comment by baibizhe** [comment]
Hello . Would you mind showing which code we need to run in order to get depth?
