### ISSUE TITLE
How to understand the intrinsic mat (not exactly same as defined in computer vision)

### ISSUE THREAD

**Issue by Guptajakala** [BachiLi/redner#83]
I found this [issue](https://github.com/BachiLi/redner/issues/66), but I'm still unable to fully understand what is the intrinsic mat here. Say if have have intrinsic params: fx, fy, fx, cy. In computer vision, we define intrinsic mat as 
```
K = [fx, 0, cx]
    [0, fy, cy]
    [0 , 0, 1]
```
So  after multiplying this K with a point already transformed in cam space x' and normalize by Z, we get first two coordinates 
```
u = fx * X/Z + cx
v = fy * Y/Z + cy
```
Which is obviously not in the range of [-1, 1/aspect_ratio) x [1, -1/aspect_ratio). 
How to correctly associate the fx, fy, fx, cy with your intrinsic mat here?

**Comment by BachiLi** [comment]
I believe it is exactly what you describe (except I'm not sure where the common camera models factor the aspect ratio in). Any `u, v` outside of the range will be clipped. If you're interested, the `camera_to_screen` function in `camera.h` implements the process you just described.

**Comment by Guptajakala** [comment]
I think I now understand what makes the difference. The fx,fy,cx,cy you are using will convert to the range [-1, 1/aspect_ratio) x [1, -1/aspect_ratio), whereas the fx,fy,cx,cy I'm using will convert to [0,W)x[0,H)

**Comment by chongli-uw** [comment]
@Guptajakala I am facing the exact same issue, can you please describe how to convert the camera intrinsics 
```
K = [fx, 0, cx]
    [0, fy, cy]
    [0 , 0, 1]
```

 to the `intrinsic_mat `in `pyrender.Camera` object using equations?

**Comment by angusev** [comment]
@chongli-uw 👋 Can I ask you if you have found the solution? I got stuck in the exactly same point, can't get the idea how to convert K to `intrinsic_mat`. I would be truly thankful if you could help to overcome this obstacle

**Comment by lith0613** [comment]
> @chongli-uw 👋 Can I ask you if you have found the solution? I got stuck in the exactly same point, can't get the idea how to convert K to `intrinsic_mat`. I would be truly thankful if you could help to overcome this obstacle

Hi, can you share your method about how to transform the R,t and the camera K into the correct value in Redner ? I am puzzled as [issue 150](https://github.com/BachiLi/redner/issues/150). I also want to sen the extrinsic and intrinsic matrix into Redner, but can not get correct result.

**Comment by xuexiaoxiaohu** [comment]
> @Guptajakala I am facing the exact same issue, can you please describe how to convert a known camera intrinsics
> 
> ```
> K = [fx, 0, cx]
>     [0, fy, cy]
>     [0 , 0, 1]
> ```
> 
> to the `intrinsic_mat `in `pyrender.Camera` object using equations? Your help is much appreciated!


> I believe it is exactly what you describe if you think in the homogeneous coordinates (except I'm not sure where the common camera models factor the aspect ratio in). In my code the normalization happens only after the multiplication of K (but in the homogeneous coordinates this shouldn't matter), and any `u, v` after normalization outside of the range will be clipped. If you're interested, the `camera_to_screen` function in `camera.h` implements the process you just described. You might also be interested in the `sample_primary` function which is the inverse of that.

I am very interested in your work, and i have the same problem , how to convert a known camera intrinsics

K = [fx, 0, cx]
    [0, fy, cy]
    [0 , 0, 1]
to the intrinsic_mat in pyrender.Camera object using equations? Your help is much appreciated!

**Comment by xuexiaoxiaohu** [comment]
> @chongli-uw 👋 Can I ask you if you have found the solution? I got stuck in the exactly same point, can't get the idea how to convert K to `intrinsic_mat`. I would be truly thankful if you could help to overcome this obstacle

Hi, have you solve this problem?

**Comment by xuexiaoxiaohu** [comment]
> I think I now understand what makes the difference. The fx,fy,cx,cy you are using will convert to the range [-1, 1/aspect_ratio) x [1, -1/aspect_ratio), whereas the fx,fy,cx,cy I'm using will convert to [0,W)x[0,H)

Hello, I am very interested in your convertion. Can you share the way to convert [0,W)x[0,H) to the he range [-1, 1/aspect_ratio) x [1, -1/aspect_ratio). Look forward to your reply ! Thanks a lot!
