### ISSUE TITLE
Could you add an option to disable "print_timing"?

### ISSUE THREAD

**Issue by Guptajakala** [BachiLi/redner#85]
Hi,

I found here enables the printing of time.
https://github.com/BachiLi/redner/blob/bff1f57f097eb7bb4fa556c0950c5078c19dca57/pyredner/render_pytorch.py#L30

During training, it's a little annoying to see it in every step. Could you add an option to disable this?

**Comment by BachiLi** [comment]
Add `pyredner.render_pytorch.print_timing = False` in your code.

**Comment by Guptajakala** [comment]
@BachiLi Oh, didn't realize there is already an option. Thank you!
