### ISSUE TITLE
Camera Resolution degrades image quality on Tensorflow version

### ISSUE THREAD

**Issue by icedoom888** [BachiLi/redner#90]
Hello @BachiLi!
redner_tensoflow produces different images depending on camera resolution. 
Artifacts get more evident the smaller the resolution.
There seems to be an error in how the tf version works with angles. 
I ran the following code on both pytorch and tensorflow, you can see the difference in the produced images.
Please note that also changing the camera's FOV produces similar artifacts.

### Pytorch
```
import os
os.environ["CUDA_VISIBLE_DEVICES"]='0'
import torch
import pyredner as pyredner
pyredner.set_use_gpu(True)

mesh_path = "mesh.obj"
resolution = [300, 400]

objects = pyredner.load_obj(mesh_path, return_objects=True)
object = objects[0]

camera = pyredner.automatic_camera_placement([object], resolution = resolution)
camera.position += 2* (camera.look_at - camera.position)
scene = pyredner.Scene(camera = camera, objects = [object])
img = pyredner.render_albedo(scene)
img = torch.flip(img, [0])

res = 'torch_res_%dx%d.png' % (resolution[0], resolution[1])
pyredner.imwrite(img.cpu(), res)
```
### Tensorflow
```
import os
os.environ["CUDA_VISIBLE_DEVICES"]='0'
os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'
import tensorflow as tf
import pyredner_tensorflow as pyredner
pyredner.set_use_gpu(True)

mesh_path = "mesh.obj"
resolution = [300, 400]

objects = pyredner.load_obj(mesh_path, return_objects=True)
object = objects[0]

camera = pyredner.automatic_camera_placement([object], resolution = resolution)
camera.position += 2* (camera.look_at - camera.position)
scene = pyredner.Scene(camera = camera, objects = [object])
img = pyredner.render_albedo(scene)
img = tf.image.flip_up_down(img)

res = 'tf_res_%dx%d.png' % (resolution[0], resolution[1])
pyredner.imwrite(img.cpu(), res)
```

- Res 3000x4000:
##### Pytorch
![torch_res_3000x4000](https://user-images.githubusercontent.com/9220778/72265121-3ab2c500-361c-11ea-8998-f14900bf5646.png)
##### Tensorflow
![tf_res_3000x4000](https://user-images.githubusercontent.com/9220778/72265166-4d2cfe80-361c-11ea-83e1-0d1474d30c8d.png)

- Res 900x1200:
##### Pytorch
![torch_res_900x1200](https://user-images.githubusercontent.com/9220778/72265242-7b124300-361c-11ea-9e82-79104e623c15.png)
 ##### Tensorflow
![tf_res_900x1200](https://user-images.githubusercontent.com/9220778/72265286-8bc2b900-361c-11ea-8b6c-a0282e78c835.png)

- Res 300x400:
##### Pytorch
![torch_res_300x400](https://user-images.githubusercontent.com/9220778/72265322-9e3cf280-361c-11ea-9514-df726e3ff358.png)
##### Tensorflow
![tf_res_300x400](https://user-images.githubusercontent.com/9220778/72265337-a4cb6a00-361c-11ea-9456-fe32192d0fa6.png)

**Comment by BachiLi** [comment]
Looks like a bug in mipmapping. Let me check later.

**Comment by BachiLi** [comment]
Can't reproduce this with my teapots. Can you provide me your object file?

**Comment by tetterl** [comment]
```
import pyredner_tensorflow as pyredner

objects = pyredner.load_obj('teapot/teapot.obj', return_objects=True)
for res in [64, 128, 256, 512, 1024, 2048]:
    camera = pyredner.automatic_camera_placement(objects, resolution=(res, res))
    scene = pyredner.Scene(camera=camera, objects=objects)
    img = pyredner.render_albedo(scene)
    pyredner.imwrite(img, str(res) + '.png')
```
Standard teapot with texture replaced by: https://en.wikipedia.org/wiki/File:Tiling_procedural_textures.jpg
[teapot.zip](https://github.com/BachiLi/redner/files/4067259/teapot.zip)

Maybe the problem only occurs with RGB textures and not with grayscale textures.

**Comment by tetterl** [comment]
Fixed in https://github.com/BachiLi/redner/pull/94

**Comment by BachiLi** [comment]
I just found the same bug. Already pushed.

**Comment by icedoom888** [comment]
Thank you very much for the support! Will test this tomorrow!
