### ISSUE TITLE
Slow TensorFlow Scene construction

### ISSUE THREAD

**Issue by tetterl** [BachiLi/redner#96]
The Scene constructions takes >5x longer (CPU and GPU) in TensorFlow compared to PyTorch (see: https://colab.research.google.com/drive/1Km8G5j_UY3cprqBv_SO9eSBhLcBunodf). Thus the whole rendering process is slowed done by ~2x.

Shouldn't be there hardly any difference since the constructions happens in the compiled code? Might there be a memory problem?

PS: The timings on colab for the TF code are sometimes as good as the PyTorch ones. On my local machine (Titan X) they are consistently worse.
```
Scene construction, time: 0.05458 s
Forward pass, time: 0.01490 s
Scene construction, time: 0.02611 s
Forward pass, time: 0.01857 s
Scene construction, time: 0.02685 s
Forward pass, time: 0.01669 s
Scene construction, time: 0.02635 s
Forward pass, time: 0.01906 s
Scene construction, time: 0.02603 s
Forward pass, time: 0.02015 s
Scene construction, time: 0.02366 s
Forward pass, time: 0.01652 s
Scene construction, time: 0.02451 s
Forward pass, time: 0.01572 s
Scene construction, time: 0.02444 s
Forward pass, time: 0.01743 s
Scene construction, time: 0.02354 s
Forward pass, time: 0.01468 s
Scene construction, time: 0.02297 s
Forward pass, time: 0.01384 s
TensorFlow Batch Rendering: 0.5128738880157471
```
```
Scene construction, time: 0.03211 s
Forward pass, time: 0.01586 s
Scene construction, time: 0.00357 s
Forward pass, time: 0.01539 s
Scene construction, time: 0.00360 s
Forward pass, time: 0.01586 s
Scene construction, time: 0.00356 s
Forward pass, time: 0.01563 s
Scene construction, time: 0.01273 s
Forward pass, time: 0.02032 s
Scene construction, time: 0.00590 s
Forward pass, time: 0.01606 s
Scene construction, time: 0.00396 s
Forward pass, time: 0.01613 s
Scene construction, time: 0.00355 s
Forward pass, time: 0.01596 s
Scene construction, time: 0.00356 s
Forward pass, time: 0.01564 s
Scene construction, time: 0.00348 s
Forward pass, time: 0.01388 s
PyTorch Batch Rendering: 0.27298808097839355
```

**Comment by BachiLi** [comment]
This construction happens in Python fully. The C++ scene construction happens in the forward rendering pass (since the ray tracing acceleration structure needs to be updated every iteration).

I'm not sure what happens here though. Most likely tensorflow does some unnecessary copy.

**Comment by BachiLi** [comment]
Interesting. Not sure what happened here. I'll need to profile this in more detail to know why. I don't know any "memory problems" that can cause this without crashing but who knows.

**Comment by BachiLi** [comment]
This is not a bug. The time in TensorFlow is spent on constructing the edge acceleration structures for secondary visibility. In PyTorch I detect whether that acceleration structure is required or not, and disable the data structure building if it is not necessary. In TensorFlow this is impossible since the API does not provide this information (the equivalent of PyTorch's `.requires_grad`).

**Comment by BachiLi** [comment]
As a workaround, if you are 100% sure you don't need the data structure, you can pass `use_secondary_edge_sampling=False` in `serialize_scene` to avoid building the data structure.

**Comment by tetterl** [comment]
Ok thanks for explaining. Is it correct that secondary edge sampling is only needed for global effects such as global illumination, shadows, ...? I.e. only rendering the albedo shouldn't use use secondary edge sampling? Or in other words rendering with `max_bounces=0` should use `use_secondary_edge_sampling=False` (not the case at the moment thus I guess my conclusion is not correct)

**Comment by BachiLi** [comment]
You are correct -- if you set `max_bounces=0` it is safe to set `use_secondary_edge_sampling=False`. I was just too lazy to add this.

**Comment by tetterl** [comment]
I'll have a look if you're not already looking into it.

**Comment by BachiLi** [comment]
> I'll have a look if you're not already looking into it.

That'll be helpful. Thanks!
